"""
Courier Tracking System - Main Flask Application
Author: Generated by Claude
"""

from flask import Flask, render_template, request, redirect, url_for, session, jsonify, flash
from database import init_db, get_db
import hashlib
import os
from datetime import datetime

app = Flask(__name__)
app.secret_key = os.urandom(24)  # Secret key for session management

# ─── HELPER FUNCTIONS ────────────────────────────────────────────────────────

def hash_password(password):
    """Hash a password using SHA-256."""
    return hashlib.sha256(password.encode()).hexdigest()

def login_required(f):
    """Decorator to protect admin routes."""
    from functools import wraps
    @wraps(f)
    def decorated(*args, **kwargs):
        if 'admin_logged_in' not in session:
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated

# ─── AUTH ROUTES ─────────────────────────────────────────────────────────────

@app.route('/')
def index():
    """Redirect root to tracking page."""
    return redirect(url_for('track'))

@app.route('/login', methods=['GET', 'POST'])
def login():
    """Admin login page."""
    if request.method == 'POST':
        username = request.form.get('username', '').strip()
        password = request.form.get('password', '')
        db = get_db()
        admin = db.execute(
            'SELECT * FROM admins WHERE username = ? AND password = ?',
            (username, hash_password(password))
        ).fetchone()
        if admin:
            session['admin_logged_in'] = True
            session['admin_username'] = username
            return redirect(url_for('dashboard'))
        else:
            flash('Invalid username or password.', 'error')
    return render_template('login.html')

@app.route('/logout')
def logout():
    """Log out admin."""
    session.clear()
    return redirect(url_for('login'))

# ─── ADMIN DASHBOARD ─────────────────────────────────────────────────────────

@app.route('/dashboard')
@login_required
def dashboard():
    """Admin dashboard with stats and recent updates."""
    db = get_db()
    total      = db.execute('SELECT COUNT(*) FROM shipments').fetchone()[0]
    delivered  = db.execute("SELECT COUNT(*) FROM shipments WHERE status='Delivered'").fetchone()[0]
    in_transit = db.execute("SELECT COUNT(*) FROM shipments WHERE status='In Transit'").fetchone()[0]
    pending    = db.execute("SELECT COUNT(*) FROM shipments WHERE status='Pending'").fetchone()[0]
    out_for    = db.execute("SELECT COUNT(*) FROM shipments WHERE status='Out for Delivery'").fetchone()[0]
    shipped    = db.execute("SELECT COUNT(*) FROM shipments WHERE status='Shipped'").fetchone()[0]

    recent_updates = db.execute('''
        SELECT th.*, s.tracking_id, s.receiver_name
        FROM tracking_history th
        JOIN shipments s ON th.shipment_id = s.id
        ORDER BY th.timestamp DESC LIMIT 10
    ''').fetchall()

    # Delayed: In Transit or Shipped for >5 days
    delayed = db.execute('''
        SELECT * FROM shipments
        WHERE status IN ('In Transit','Shipped','Pending')
        AND julianday('now') - julianday(created_at) > 5
        ORDER BY created_at ASC
    ''').fetchall()

    stats = {
        'total': total, 'delivered': delivered, 'in_transit': in_transit,
        'pending': pending, 'out_for': out_for, 'shipped': shipped
    }
    return render_template('dashboard.html', stats=stats,
                           recent_updates=recent_updates, delayed=delayed)

# ─── SHIPMENT MANAGEMENT ─────────────────────────────────────────────────────

@app.route('/add-shipment', methods=['GET', 'POST'])
@login_required
def add_shipment():
    """Add a new shipment."""
    if request.method == 'POST':
        import uuid
        tracking_id   = 'TRK' + uuid.uuid4().hex[:8].upper()  # Auto-generate tracking ID
        sender_name   = request.form.get('sender_name', '').strip()
        receiver_name = request.form.get('receiver_name', '').strip()
        origin        = request.form.get('origin', '').strip()
        destination   = request.form.get('destination', '').strip()
        sender_contact   = request.form.get('sender_contact', '').strip()
        receiver_contact = request.form.get('receiver_contact', '').strip()
        weight        = request.form.get('weight', '').strip()
        description   = request.form.get('description', '').strip()

        db = get_db()
        db.execute('''
            INSERT INTO shipments
            (tracking_id, sender_name, receiver_name, origin, destination,
             sender_contact, receiver_contact, weight, description, status, created_at)
            VALUES (?,?,?,?,?,?,?,?,?,'Pending', datetime('now'))
        ''', (tracking_id, sender_name, receiver_name, origin, destination,
              sender_contact, receiver_contact, weight, description))
        # Get last inserted shipment id
        shipment_id = db.execute('SELECT last_insert_rowid()').fetchone()[0]
        # Log initial tracking history
        db.execute('''
            INSERT INTO tracking_history (shipment_id, status, location, notes, timestamp)
            VALUES (?, 'Pending', ?, 'Shipment created', datetime('now'))
        ''', (shipment_id, origin))
        db.commit()
        flash(f'Shipment created! Tracking ID: {tracking_id}', 'success')
        return redirect(url_for('manage_shipments'))

    return render_template('add_shipment.html')

@app.route('/manage-shipments')
@login_required
def manage_shipments():
    """List all shipments with search and filter."""
    db = get_db()
    search = request.args.get('search', '').strip()
    status_filter = request.args.get('status', '').strip()

    query = 'SELECT * FROM shipments WHERE 1=1'
    params = []
    if search:
        query += ' AND (tracking_id LIKE ? OR sender_name LIKE ? OR receiver_name LIKE ?)'
        params += [f'%{search}%', f'%{search}%', f'%{search}%']
    if status_filter:
        query += ' AND status = ?'
        params.append(status_filter)
    query += ' ORDER BY created_at DESC'

    shipments = db.execute(query, params).fetchall()
    return render_template('manage_shipments.html', shipments=shipments,
                           search=search, status_filter=status_filter)

@app.route('/update-status/<int:shipment_id>', methods=['GET', 'POST'])
@login_required
def update_status(shipment_id):
    """Update shipment status and log to history."""
    db = get_db()
    shipment = db.execute('SELECT * FROM shipments WHERE id=?', (shipment_id,)).fetchone()
    if not shipment:
        flash('Shipment not found.', 'error')
        return redirect(url_for('manage_shipments'))

    if request.method == 'POST':
        new_status = request.form.get('status')
        location   = request.form.get('location', '').strip()
        notes      = request.form.get('notes', '').strip()

        db.execute('UPDATE shipments SET status=? WHERE id=?', (new_status, shipment_id))
        db.execute('''
            INSERT INTO tracking_history (shipment_id, status, location, notes, timestamp)
            VALUES (?, ?, ?, ?, datetime('now'))
        ''', (shipment_id, new_status, location, notes))
        db.commit()
        flash('Shipment status updated successfully!', 'success')
        return redirect(url_for('manage_shipments'))

    history = db.execute(
        'SELECT * FROM tracking_history WHERE shipment_id=? ORDER BY timestamp DESC',
        (shipment_id,)
    ).fetchall()
    return render_template('update_status.html', shipment=shipment, history=history)

@app.route('/delete-shipment/<int:shipment_id>', methods=['POST'])
@login_required
def delete_shipment(shipment_id):
    """Delete a shipment and its history."""
    db = get_db()
    db.execute('DELETE FROM tracking_history WHERE shipment_id=?', (shipment_id,))
    db.execute('DELETE FROM shipments WHERE id=?', (shipment_id,))
    db.commit()
    flash('Shipment deleted successfully.', 'success')
    return redirect(url_for('manage_shipments'))

# ─── PUBLIC TRACKING ─────────────────────────────────────────────────────────

@app.route('/track', methods=['GET', 'POST'])
def track():
    """Public tracking page."""
    shipment = None
    history  = []
    tracking_id = request.args.get('tracking_id', '').strip()

    if tracking_id:
        db = get_db()
        shipment = db.execute(
            'SELECT * FROM shipments WHERE tracking_id=?', (tracking_id,)
        ).fetchone()
        if shipment:
            history = db.execute(
                'SELECT * FROM tracking_history WHERE shipment_id=? ORDER BY timestamp ASC',
                (shipment['id'],)
            ).fetchall()
        else:
            flash('No shipment found with that tracking ID.', 'error')

    return render_template('track.html', shipment=shipment,
                           history=history, tracking_id=tracking_id)

# ─── API ENDPOINTS ────────────────────────────────────────────────────────────

@app.route('/api/track/<tracking_id>')
def api_track(tracking_id):
    """JSON API endpoint for tracking."""
    db = get_db()
    shipment = db.execute(
        'SELECT * FROM shipments WHERE tracking_id=?', (tracking_id,)
    ).fetchone()
    if not shipment:
        return jsonify({'error': 'Not found'}), 404
    history = db.execute(
        'SELECT * FROM tracking_history WHERE shipment_id=? ORDER BY timestamp ASC',
        (shipment['id'],)
    ).fetchall()
    return jsonify({
        'shipment': dict(shipment),
        'history': [dict(h) for h in history]
    })

# ─── MAIN ─────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    init_db()
    app.run(debug=True)
